### ISSUE TITLE
Adding custom methods to d3 won't work without explicitly importing the node build

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/bluprint_graphics-rig#18]
So Gurman found a nifty bug...

She was trying to add some custom methods onto the d3 global.

```javascript
import * as d3 from 'd3';

d3.selection.prototype.newMethod = () => ...
```

`newMethod` would work in dev but with a warning. But when we built,  it was gone.

The solution was to explicitly import the _node_ build of d3:

```javascript
import * as d3 from 'd3/dist/d3.node.js';
```

... but this feels hacky AF.

Putting this ticket here for anyone to tell me a better way...

**Comment by manas271196** [comment]
I tested this a bit today. this is what i THINK is happening.

i played with the specific case Gurman had in [this file](https://github.com/tr/graphics_coronavirus-country-pages/blob/master/src/js/tools/d3.js)

the line
```js
import * as d3 from 'd3'
```
imports a read only object. so you can't add properties to that directly.

the node build works because it's not read only. that method will also work with the non node build like (assuming my understanding of the "non node build" is correct):

```js
import * as d3 from 'd3/dist/d3.js';
```

this is explained a bit here: https://exploringjs.com/es6/ch_modules.html#_in-es6-imports-are-live-read-only-views-on-exported-values

The way to do it would be this:

```js
import * as d3 from 'd3';

d3.methodA = () => ...
...
export default Object.assign(d3, {methodA})
```

note that the line
```js
d3.selection.prototype.methodB = () => ...
```

will work without a problem in both cases. I'm not entirely sure why, but it might be because of this line in the link above:

> Note that while you can’t change the values of imports, you can change the objects that they are referring to.

**Comment by MatthewWeberTR** [comment]
Strong recommend NOT importing all of d3, but doing an object.assign with the modules you want.  

If you aren't making a map, the weight of all the d3 mapping stuff is INTENSE.

PLUS will have the add on effect of allowing you to add any properties you like.

```
let d3 = Object.assign(
  require('d3-format'),
  require('d3-fetch'),
  require('d3-time-format')
);
```

**Comment by hobbes7878** [comment]
I _think_ Webpack should be treeshaking some of that d3 clutter out these days, but I never know with Bostock libs, honestly... Definitely best to roll your own.
